resource_types:

  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
      tag: 0.11.14

resources:

  - name: terraforming-azure-repository
    type: git
    source:
      branch: v0.55.0
      uri: git@github.com:pivotal-cf/terraforming-azure.git
      private_key: ((git_ssh_key))

  - name: terraform
    type: terraform
    source:
      env_name: ((env_name))
      backend_type: azurerm
      backend_config:
        container_name: ((azure_terraform_container_name))
        key: ((env_name))
        storage_account_name: ((azure_terraform_storage_account_name))
        resource_group_name: ((azure_terraform_resource_group_name))
        access_key: ((azure_access_key))
      delete_on_failure: false
      vars:
        cf_storage_account_name: ((azure_cf_storage_account_name))
        env_name: ((env_name))
        location: ((location))
        subscription_id: ((azure_subscription_id))
        tenant_id: ((azure_tenant_id))
        client_id: ((azure_client_id))
        client_secret: ((azure_client_secret))
        dns_subdomain: ((env_name))
        dns_suffix: ((dns_suffix))
        ops_manager_image_uri: ((ops_manager_image_uri))

jobs:
  - name: terraform-pas-apply
    plan:
    - get: terraforming-azure-repository
      trigger: false
    - put: terraform
      params:
        env_name: ((env_name))
        terraform_source: terraforming-azure-repository/terraforming-pas

  - name: terraform-pks-apply
    plan:
      - get: terraforming-azure-repository
        trigger: false
      - put: terraform
        params:
          env_name: ((env_name))
          terraform_source: terraforming-azure-repository/terraforming-pks

  - name: terraform-destroy
    plan:
    - get: terraforming-azure-repository
      trigger: false
    - put: terraform
      get_params:
        action: destroy
      params:
        action: destroy
        env_name: ((env_name))
        terraform_source: terraforming-azure-repository/terraforming-pas
