resource_types:

  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
      tag: 0.12.3

resources:

  - name: git
    type: git
    source:
      branch: master
      uri: ((git_uri))
      private_key: ((my_ssh_key))

  - name: terraform
    type: terraform
    source:
      env_name: ((env_name))
      backend_type: s3
      backend_config:
        bucket: ((bucket))
        key: ((key))
        region: ((region))
        access_key: ((storage_access_key))
        secret_key: ((storage_secret_key))
      delete_on_failure: false
      vars:
        contact_email: ((contact_email))
        location: ((location))
        subscription_id: ((subscription_id))
        tenant_id: ((tenant_id))
        client_id: ((client_id))
        client_secret: ((client_secret))
        dns_root: ((dns_root))
        dns_sub: ((dns_sub))
        dns_suffix: ((dns_suffix))
        ops_manager_image_uri: ((ops_manager_image_uri))
        cloudflare_email: ((cloudflare_email))
        cloudflare_key: ((cloudflare_key))

jobs:
  - name: terraform-apply
    plan:
    - get: git
      trigger: false
    - put: terraform
      params:
        env_name: ((env_name))
        terraform_source: git/terraforming-pas

  - name: terraform-destroy
    plan:
    - get: git
      trigger: false
    - put: terraform
      get_params:
        action: destroy
      params:
        action: destroy
        env_name: ((env_name))
        terraform_source: git/terraforming-pas
