resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
      tag: latest

resources:
  - name: paving
    type: git
    source:
      branch: master
      uri: git@github.com:pivotal/paving.git
      private_key: ((git_ssh_key))

  - name: terraform
    type: terraform
    source:
      env_name: ((environment_name))
      backend_type: s3
      backend_config:
        bucket: ((aws_terraform_bucket))
        key: terraform.tfstate
        region: ((aws_terraform_bucket_region))
        access_key: ((aws_access_key))
        secret_key: ((aws_secret_key))
      delete_on_failure: true
      vars:
        environment_name: ((environment_name))
        region: ((region))
        dns_suffix: ((dns_suffix))
        hosted_zone: ((hosted_zone))
        availability_zones: ((availability_zones))
        access_key: ((aws_access_key))
        secret_key: ((aws_secret_key))

jobs:
  - name: apply-show-output-destroy
    plan:
      - get: paving
        trigger: true
      - put: terraform
        params:
          env_name: ((environment_name))
          terraform_source: paving/aws
      - task: show-outputs
        config:
          platform: linux
          inputs:
            - name: terraform
          run:
            path: /bin/sh
            args:
              - -c
              - |
                echo "name: $(cat terraform/name)"
                echo "metadata: $(cat terraform/metadata)"
      - put: terraform
        get_params:
          action: destroy
        params:
          action: destroy
          env_name: ((environment_name))
          terraform_source: paving/aws